echo "TexLive Release Version: $(tlmgr version | tail -n 1 | cut -f5- -d' ')"
echo "tlmgr (TeX Live Manager) Version: $(tlmgr version | head -n 1 | cut -f3- -d' ')"
echo "latexindent Version: $(latexindent --version)"
echo "latexmk Version: $(latexmk -version | tail -n 1 | cut -f8 -d' ')"
echo "Available Helpful Commands:"
echo " * To update all LaTeX packages, run:"
echo "       tlmgr update --all"
echo " * To install a specific LaTeX package, use:"
echo "       tlmgr install packagename"
echo "       texhash"
echo " * To install an operating system package, execute:"
echo "       sudo apt-get install -y packagename"

