version: "3.2"

services:
  vscode:
    build: .
    image: latexdevcontainer
    volumes:
      - ../:/workspace
      - /var/run/docker.sock:/var/run/docker.sock
      - ~/.ssh:/root/.ssh
      - ~/.zsh_history:/root/.zsh_history:z
      - /home/nano/.gitconfig:/root/.gitconfig
    environment:
      - TZ=Germany/Berlin # Make sure to set your timezone, e.g., TZ=America/New_York
    entrypoint: ["zsh", "-c", "while sleep 1000; do :; done"]
